name: Update

on:
  push:
    branches: [ ci ]
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update
    steps:
      - uses: actions/checkout@v2
        name: Checkout CI code
        with:
          ref: ci

      - name: Checkout readme
        uses: actions/checkout@v2
        with:
          ref: main
          path: dist

      - name: Just update
        run: |
          node index.mjs
