on:
  push:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Checkout readme
        uses: actions/checkout@v2
        with:
          branch: main
          path: dist

      - name: Just update
        run: |
          node index.mjs
